language: ruby
rvm:
  - 2.5.3

install:
  - bundle install

script: rails test

before_deploy:
  - if[["$TRAVIS_PULL_REQUEST" == "true"]]; then exit 0; fi
  - zip -r pair-goal-api *
  - mkdir -p deploy
  - mv pair-goal-api deploy/pair-goal-api.zip

deploy:
  - provider: s3
    local_dir: deploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: pair-goal-travis
    region: ap-northeast-2
    skip_cleanup: true 
    acl: public_read
    wait-until-deployed: true
    on:
      repo: pair-goal/api-backend
      branch: master