language: ruby
rvm:
  - 2.5.3

script:
  - mkdir gem

install:
  - bundle install --path ./gem

script:
  - chmod 755 bin/rails
  - bin/rails test

before_deploy:
  - if ["$TRAVIS_PULL_REQUEST" == "true"]; then exit 0; fi
  - zip -r -q pair-goal-api *
  - mkdir -p deploy
  - mv pair-goal-api.zip deploy/pair-goal-api.zip

deploy:
  - provider: s3
    local_dir: deploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: pair-goal-travis
    region: ap-northeast-2
    skip_cleanup: true 
    acl: public_read
    wait-until-deployed: true
    on:
      repo: pair-goal/api-backend
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: pair-goal-travis 
    key: pair-goal-api.zip
    bundle_type: zip
    application: travis-codeDeploy-service
    deployment_group: travis-codeDeploy-group
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: pair-goal/api-backend
      branch: master