language: ruby
rvm:
  - 2.5.3

install:
  - bundle install

deploy:
  - provider: s3
    script: rails test
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: pair-goal-travis
    region: ap-northeast-2
    skip_cleanup: true 
    acl: public_read
    wait-until-deployed: true
    on:
      repo: pair-goal/api-backend
      branch: master